#!/usr/bin/env python3
"""
14-diff-meth.py - Differential Methylation Analysis

This script identifies differentially methylated regions (DMRs) between 
Siscowet and Lean lake trout (Salvelinus namaycush) subspecies using 
PacBio HiFi methylation data.

Analysis Pipeline:
1. Download pre-computed CpG methylation data from gannet server
   (generated by 10-mCG-call.Rmd using modkit pileup)
2. Merge methylation data across all samples
3. Perform statistical testing for differential methylation
4. Identify differentially methylated CpGs (DMCs)
5. Define differentially methylated regions (DMRs)
6. Annotate DMRs with gene information

Sample Groups:
- LEAN: bc2041, bc2069, bc2070, bc2068
- SISCOWET: bc2071, bc2073, bc2072, bc2096

Data Source:
https://gannet.fish.washington.edu/v1_web/owlshell/bu-github/project-lake-trout/analyses/10-mCG-call/

Author: Generated for project-lake-trout
Date: 2025-12-07
"""

import os
import subprocess
import gzip
import numpy as np
import pandas as pd
from pathlib import Path
from scipy import stats
from statsmodels.stats.multitest import multipletests
from collections import defaultdict

# =============================================================================
# Configuration
# =============================================================================

# Define samples by subspecies
SAMPLES_LEAN = ["bc2041", "bc2069", "bc2070", "bc2068"]
SAMPLES_SISCOWET = ["bc2071", "bc2073", "bc2072", "bc2096"]
SAMPLES = SAMPLES_LEAN + SAMPLES_SISCOWET

# Sample to group mapping
SAMPLE_GROUPS = {s: "LEAN" for s in SAMPLES_LEAN}
SAMPLE_GROUPS.update({s: "SISCOWET" for s in SAMPLES_SISCOWET})

# Paths (relative to code directory)
BASE_DIR = Path(__file__).parent.parent
METH_DATA_DIR = BASE_DIR / "analyses" / "10-mCG-call"
OUTPUT_DIR = BASE_DIR / "analyses" / "14-diff-meth"
REFERENCE = BASE_DIR / "data" / "GCF_016432855.1_SaNama_1.0_genomic.fa"
GENES_BED = BASE_DIR / "data" / "20220818-snam-GCF_016432855.1_SaNama_1.0_genes.bed"

# Remote data URL
GANNET_URL = "https://gannet.fish.washington.edu/v1_web/owlshell/bu-github/project-lake-trout/analyses/10-mCG-call"

# Analysis parameters
# Note: Using cov10 files which are pre-filtered for coverage >= 10
MIN_COVERAGE = 10       # Data already filtered for this threshold
MIN_SAMPLES = 3         # Minimum samples per group with data
DIFF_THRESHOLD = 0.15   # Minimum methylation difference (15%)
P_VALUE_THRESHOLD = 0.05
Q_VALUE_THRESHOLD = 0.10
DMR_MERGE_DISTANCE = 250  # bp - merge CpGs within this distance
MIN_CPGS_PER_DMR = 3    # Minimum CpGs to call a DMR
THREADS = 16

# =============================================================================
# Helper Functions
# =============================================================================

def run_command(cmd, description="", check=True):
    """Run a shell command and handle errors."""
    print(f"  Running: {description or cmd[:80]}...")
    try:
        result = subprocess.run(
            cmd, shell=True, check=check,
            capture_output=True, text=True
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        print(f"  ERROR: {e.stderr}")
        if check:
            raise
        return None

def ensure_directory(path):
    """Create directory if it doesn't exist."""
    Path(path).mkdir(parents=True, exist_ok=True)

def file_exists_and_nonempty(filepath):
    """Check if file exists and is not empty."""
    path = Path(filepath)
    return path.exists() and path.stat().st_size > 0

# =============================================================================
# Step 1: Download CpG Methylation Data from Gannet Server
# =============================================================================

def download_methylation_data():
    """
    Download pre-computed methylation data from gannet server.
    
    Data was generated by 10-mCG-call.Rmd using modkit pileup.
    We use the .cov10.bedGraph files which are:
    - Pre-filtered for coverage >= 10
    - Smaller file sizes for faster processing
    
    Source: https://gannet.fish.washington.edu/v1_web/owlshell/bu-github/project-lake-trout/analyses/10-mCG-call/
    """
    print("\n" + "="*60)
    print("Step 1: Downloading CpG methylation data from gannet server")
    print("="*60)
    
    # Ensure methylation data directory exists
    ensure_directory(METH_DATA_DIR)
    
    downloaded = 0
    skipped = 0
    
    for sample in SAMPLES:
        # Use the coverage-filtered bedGraph files (much smaller)
        bedgraph_file = METH_DATA_DIR / f"{sample}.cov10.bedGraph"
        
        if file_exists_and_nonempty(bedgraph_file):
            print(f"  {sample}: Data already exists, skipping download...")
            skipped += 1
            continue
        
        # Download the bedGraph file
        url = f"{GANNET_URL}/{sample}.cov10.bedGraph"
        print(f"  Downloading {sample}.cov10.bedGraph...")
        
        cmd = f"wget -q -O {bedgraph_file} {url}"
        try:
            run_command(cmd, f"Downloading {sample}")
            if file_exists_and_nonempty(bedgraph_file):
                downloaded += 1
                print(f"    Downloaded successfully.")
            else:
                print(f"    WARNING: Download failed or empty file for {sample}")
        except Exception as e:
            print(f"    ERROR downloading {sample}: {e}")
    
    print(f"\n  Downloaded: {downloaded} files")
    print(f"  Already present: {skipped} files")
    print(f"  Total available: {downloaded + skipped} / {len(SAMPLES)} samples")
    
    return downloaded + skipped

# =============================================================================
# Step 2: Parse and Merge Methylation Data
# =============================================================================

def parse_bedgraph(filepath, sample_name):
    """
    Parse bedGraph file with percent methylation.
    
    bedGraph format (4 columns):
    chrom, start, end, pct_methylation
    
    These files are already filtered for coverage >= 10 (cov10.bedGraph)
    
    Returns DataFrame with columns: chrom, pos, pct_meth
    """
    data = []
    
    if not file_exists_and_nonempty(filepath):
        print(f"  WARNING: File not found or empty: {filepath}")
        return pd.DataFrame()
    
    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('#') or line.startswith('track'):
                continue
            parts = line.strip().split('\t')
            if len(parts) < 4:
                continue
            
            try:
                chrom = parts[0]
                pos = int(parts[1])
                pct_modified = float(parts[3])
                
                data.append({
                    'chrom': chrom,
                    'pos': pos,
                    'pct_meth': pct_modified
                })
            except (ValueError, IndexError):
                continue
    
    df = pd.DataFrame(data)
    if not df.empty:
        df['sample'] = sample_name
    
    return df

def merge_methylation_data():
    """Merge methylation data from all samples into a unified matrix."""
    print("\n" + "="*60)
    print("Step 2: Merging methylation data across samples")
    print("="*60)
    
    all_data = []
    
    for sample in SAMPLES:
        # Use the coverage-filtered bedGraph files
        filepath = METH_DATA_DIR / f"{sample}.cov10.bedGraph"
        print(f"  Parsing {sample}...")
        df = parse_bedgraph(filepath, sample)
        if not df.empty:
            all_data.append(df)
            print(f"    Found {len(df):,} CpGs (pre-filtered for coverage >= {MIN_COVERAGE})")
    
    if not all_data:
        print("  ERROR: No methylation data found!")
        print("  Make sure to run the download step first or check the data directory.")
        return None
    
    # Combine all data
    combined = pd.concat(all_data, ignore_index=True)
    
    # Create methylation matrix: rows = CpG positions, columns = samples
    print("\n  Creating methylation matrix...")
    
    # Create position identifier
    combined['site_id'] = combined['chrom'] + ':' + combined['pos'].astype(str)
    
    # Pivot to wide format
    meth_matrix = combined.pivot_table(
        index='site_id',
        columns='sample',
        values='pct_meth',
        aggfunc='first'
    )
    
    # Parse site_id back to chrom and pos
    site_info = pd.DataFrame({
        'site_id': meth_matrix.index,
        'chrom': [s.split(':')[0] for s in meth_matrix.index],
        'pos': [int(s.split(':')[1]) for s in meth_matrix.index]
    }).set_index('site_id')
    
    print(f"  Total unique CpG sites: {len(meth_matrix):,}")
    print(f"  Samples in matrix: {list(meth_matrix.columns)}")
    
    # Save merged data
    output_file = OUTPUT_DIR / "methylation_matrix.csv"
    meth_matrix.to_csv(output_file)
    print(f"  Saved methylation matrix to: {output_file}")
    
    return meth_matrix, site_info

# =============================================================================
# Step 3: Differential Methylation Analysis
# =============================================================================

def differential_methylation_analysis(meth_matrix, site_info):
    """
    Perform differential methylation analysis between Lean and Siscowet.
    
    Uses Mann-Whitney U test for each CpG site.
    """
    print("\n" + "="*60)
    print("Step 3: Differential methylation analysis")
    print("="*60)
    
    lean_samples = [s for s in SAMPLES_LEAN if s in meth_matrix.columns]
    siscowet_samples = [s for s in SAMPLES_SISCOWET if s in meth_matrix.columns]
    
    print(f"  LEAN samples: {lean_samples}")
    print(f"  SISCOWET samples: {siscowet_samples}")
    
    if len(lean_samples) < MIN_SAMPLES or len(siscowet_samples) < MIN_SAMPLES:
        print(f"  ERROR: Need at least {MIN_SAMPLES} samples per group!")
        return None
    
    results = []
    
    print(f"\n  Testing {len(meth_matrix)} CpG sites...")
    
    for idx, site_id in enumerate(meth_matrix.index):
        if idx % 100000 == 0 and idx > 0:
            print(f"    Processed {idx:,} sites...")
        
        # Get methylation values for each group
        lean_vals = meth_matrix.loc[site_id, lean_samples].dropna()
        sisc_vals = meth_matrix.loc[site_id, siscowet_samples].dropna()
        
        # Skip if not enough samples have data
        if len(lean_vals) < MIN_SAMPLES or len(sisc_vals) < MIN_SAMPLES:
            continue
        
        # Calculate means
        lean_mean = lean_vals.mean()
        sisc_mean = sisc_vals.mean()
        diff = sisc_mean - lean_mean  # Positive = higher in Siscowet
        
        # Statistical test (Mann-Whitney U)
        try:
            stat, pval = stats.mannwhitneyu(lean_vals, sisc_vals, alternative='two-sided')
        except Exception:
            continue
        
        chrom = site_info.loc[site_id, 'chrom']
        pos = site_info.loc[site_id, 'pos']
        
        results.append({
            'site_id': site_id,
            'chrom': chrom,
            'pos': pos,
            'lean_mean': lean_mean,
            'siscowet_mean': sisc_mean,
            'meth_diff': diff,
            'n_lean': len(lean_vals),
            'n_siscowet': len(sisc_vals),
            'statistic': stat,
            'pvalue': pval
        })
    
    if not results:
        print("  ERROR: No valid comparisons!")
        return None
    
    df = pd.DataFrame(results)
    
    # Multiple testing correction (Benjamini-Hochberg)
    print(f"\n  Applying FDR correction to {len(df)} tests...")
    reject, qvals, _, _ = multipletests(df['pvalue'], method='fdr_bh')
    df['qvalue'] = qvals
    
    # Classify significance
    df['significant'] = (
        (df['pvalue'] < P_VALUE_THRESHOLD) & 
        (np.abs(df['meth_diff']) >= DIFF_THRESHOLD * 100)  # Convert to percentage scale
    )
    df['significant_fdr'] = (
        (df['qvalue'] < Q_VALUE_THRESHOLD) & 
        (np.abs(df['meth_diff']) >= DIFF_THRESHOLD * 100)
    )
    
    # Direction of change
    df['direction'] = np.where(df['meth_diff'] > 0, 'hyper_siscowet', 'hypo_siscowet')
    
    print(f"\n  Results summary:")
    print(f"    Total CpG sites tested: {len(df)}")
    print(f"    Significant (p < {P_VALUE_THRESHOLD}, diff >= {DIFF_THRESHOLD*100}%): {df['significant'].sum()}")
    print(f"    Significant after FDR (q < {Q_VALUE_THRESHOLD}): {df['significant_fdr'].sum()}")
    
    sig_df = df[df['significant']]
    if len(sig_df) > 0:
        print(f"    - Hypermethylated in Siscowet: {(sig_df['direction'] == 'hyper_siscowet').sum()}")
        print(f"    - Hypomethylated in Siscowet: {(sig_df['direction'] == 'hypo_siscowet').sum()}")
    
    # Save results
    output_file = OUTPUT_DIR / "differential_methylation_cpgs.csv"
    df.to_csv(output_file, index=False)
    print(f"\n  Saved all CpG results to: {output_file}")
    
    # Save significant CpGs
    sig_file = OUTPUT_DIR / "significant_dmcs.csv"
    df[df['significant']].to_csv(sig_file, index=False)
    print(f"  Saved significant DMCs to: {sig_file}")
    
    return df

# =============================================================================
# Step 4: Identify Differentially Methylated Regions (DMRs)
# =============================================================================

def identify_dmrs(dm_results):
    """
    Identify Differentially Methylated Regions (DMRs) by merging 
    nearby significant DMCs.
    """
    print("\n" + "="*60)
    print("Step 4: Identifying Differentially Methylated Regions (DMRs)")
    print("="*60)
    
    # Filter for significant DMCs
    sig_df = dm_results[dm_results['significant']].copy()
    
    if len(sig_df) == 0:
        print("  No significant DMCs found. Cannot identify DMRs.")
        return None
    
    # Sort by chromosome and position
    sig_df = sig_df.sort_values(['chrom', 'pos'])
    
    dmrs = []
    current_dmr = None
    
    print(f"  Merging {len(sig_df)} significant DMCs into regions...")
    
    for _, row in sig_df.iterrows():
        chrom = row['chrom']
        pos = row['pos']
        direction = row['direction']
        
        if current_dmr is None:
            # Start new DMR
            current_dmr = {
                'chrom': chrom,
                'start': pos,
                'end': pos + 1,
                'direction': direction,
                'cpgs': [row],
                'n_cpgs': 1
            }
        elif (chrom == current_dmr['chrom'] and 
              pos - current_dmr['end'] <= DMR_MERGE_DISTANCE and
              direction == current_dmr['direction']):
            # Extend current DMR
            current_dmr['end'] = pos + 1
            current_dmr['cpgs'].append(row)
            current_dmr['n_cpgs'] += 1
        else:
            # Save current DMR and start new one
            if current_dmr['n_cpgs'] >= MIN_CPGS_PER_DMR:
                dmrs.append(current_dmr)
            current_dmr = {
                'chrom': chrom,
                'start': pos,
                'end': pos + 1,
                'direction': direction,
                'cpgs': [row],
                'n_cpgs': 1
            }
    
    # Don't forget last DMR
    if current_dmr is not None and current_dmr['n_cpgs'] >= MIN_CPGS_PER_DMR:
        dmrs.append(current_dmr)
    
    if not dmrs:
        print(f"  No DMRs with >= {MIN_CPGS_PER_DMR} CpGs found.")
        return None
    
    # Create DMR summary DataFrame
    dmr_data = []
    for i, dmr in enumerate(dmrs):
        cpg_df = pd.DataFrame(dmr['cpgs'])
        dmr_data.append({
            'dmr_id': f"DMR_{i+1}",
            'chrom': dmr['chrom'],
            'start': dmr['start'],
            'end': dmr['end'],
            'length': dmr['end'] - dmr['start'],
            'n_cpgs': dmr['n_cpgs'],
            'direction': dmr['direction'],
            'mean_diff': cpg_df['meth_diff'].mean(),
            'mean_pvalue': cpg_df['pvalue'].mean(),
            'min_pvalue': cpg_df['pvalue'].min(),
            'lean_mean': cpg_df['lean_mean'].mean(),
            'siscowet_mean': cpg_df['siscowet_mean'].mean()
        })
    
    dmr_df = pd.DataFrame(dmr_data)
    
    print(f"\n  DMR Summary:")
    print(f"    Total DMRs identified: {len(dmr_df)}")
    print(f"    Hypermethylated in Siscowet: {(dmr_df['direction'] == 'hyper_siscowet').sum()}")
    print(f"    Hypomethylated in Siscowet: {(dmr_df['direction'] == 'hypo_siscowet').sum()}")
    print(f"    Mean CpGs per DMR: {dmr_df['n_cpgs'].mean():.1f}")
    print(f"    Mean DMR length: {dmr_df['length'].mean():.1f} bp")
    
    # Save DMRs
    output_file = OUTPUT_DIR / "dmrs.csv"
    dmr_df.to_csv(output_file, index=False)
    print(f"\n  Saved DMRs to: {output_file}")
    
    # Save as BED file
    bed_file = OUTPUT_DIR / "dmrs.bed"
    with open(bed_file, 'w') as f:
        f.write("#chrom\tstart\tend\tname\tscore\tstrand\tmeth_diff\tn_cpgs\tdirection\n")
        for _, row in dmr_df.iterrows():
            score = int(min(abs(row['mean_diff']), 100))  # Score 0-100
            strand = "+" if row['direction'] == 'hyper_siscowet' else "-"
            f.write(f"{row['chrom']}\t{row['start']}\t{row['end']}\t")
            f.write(f"{row['dmr_id']}\t{score}\t{strand}\t")
            f.write(f"{row['mean_diff']:.2f}\t{row['n_cpgs']}\t{row['direction']}\n")
    print(f"  Saved DMRs BED file to: {bed_file}")
    
    # Create separate BED files for hyper and hypo
    hyper_df = dmr_df[dmr_df['direction'] == 'hyper_siscowet']
    hypo_df = dmr_df[dmr_df['direction'] == 'hypo_siscowet']
    
    if len(hyper_df) > 0:
        hyper_bed = OUTPUT_DIR / "dmrs_hyper_siscowet.bed"
        hyper_df[['chrom', 'start', 'end', 'dmr_id', 'n_cpgs', 'mean_diff']].to_csv(
            hyper_bed, sep='\t', index=False, header=False)
        print(f"  Saved hypermethylated DMRs to: {hyper_bed}")
    
    if len(hypo_df) > 0:
        hypo_bed = OUTPUT_DIR / "dmrs_hypo_siscowet.bed"
        hypo_df[['chrom', 'start', 'end', 'dmr_id', 'n_cpgs', 'mean_diff']].to_csv(
            hypo_bed, sep='\t', index=False, header=False)
        print(f"  Saved hypomethylated DMRs to: {hypo_bed}")
    
    return dmr_df

# =============================================================================
# Step 5: Annotate DMRs with Genes
# =============================================================================

def annotate_dmrs_with_genes(dmr_df):
    """Intersect DMRs with gene annotations."""
    print("\n" + "="*60)
    print("Step 5: Annotating DMRs with gene information")
    print("="*60)
    
    if dmr_df is None or len(dmr_df) == 0:
        print("  No DMRs to annotate.")
        return None
    
    if not GENES_BED.exists():
        print(f"  WARNING: Gene annotation file not found: {GENES_BED}")
        return dmr_df
    
    # Create temporary DMR BED for bedtools
    temp_dmr_bed = OUTPUT_DIR / "temp_dmrs_for_intersect.bed"
    dmr_df[['chrom', 'start', 'end', 'dmr_id']].to_csv(
        temp_dmr_bed, sep='\t', index=False, header=False)
    
    # Run bedtools intersect
    output_file = OUTPUT_DIR / "dmrs_genes_intersect.bed"
    cmd = f"bedtools intersect -a {temp_dmr_bed} -b {GENES_BED} -wa -wb > {output_file}"
    
    try:
        run_command(cmd, "bedtools intersect DMRs with genes")
        
        if file_exists_and_nonempty(output_file):
            # Parse intersection results
            intersect_df = pd.read_csv(output_file, sep='\t', header=None)
            
            # Columns: dmr_chrom, dmr_start, dmr_end, dmr_id, gene_chrom, gene_start, gene_end, gene_name, ...
            if len(intersect_df.columns) >= 8:
                intersect_df.columns = ['dmr_chrom', 'dmr_start', 'dmr_end', 'dmr_id',
                                       'gene_chrom', 'gene_start', 'gene_end', 'gene_name'] + \
                                      [f'extra_{i}' for i in range(len(intersect_df.columns) - 8)]
                
                # Get unique genes per DMR
                dmr_genes = intersect_df.groupby('dmr_id')['gene_name'].apply(
                    lambda x: ';'.join(x.unique())
                ).reset_index()
                dmr_genes.columns = ['dmr_id', 'overlapping_genes']
                
                # Merge back to DMR table
                dmr_df = dmr_df.merge(dmr_genes, on='dmr_id', how='left')
                dmr_df['overlapping_genes'] = dmr_df['overlapping_genes'].fillna('')
                
                n_with_genes = (dmr_df['overlapping_genes'] != '').sum()
                print(f"\n  DMRs overlapping genes: {n_with_genes} / {len(dmr_df)}")
                
                # Save annotated DMRs
                output_file = OUTPUT_DIR / "dmrs_annotated.csv"
                dmr_df.to_csv(output_file, index=False)
                print(f"  Saved annotated DMRs to: {output_file}")
        else:
            print("  No gene overlaps found.")
    
    except Exception as e:
        print(f"  WARNING: Could not annotate with genes: {e}")
    
    # Clean up temp file
    if temp_dmr_bed.exists():
        temp_dmr_bed.unlink()
    
    return dmr_df

# =============================================================================
# Step 6: Generate Summary Report
# =============================================================================

def generate_summary_report(dm_results, dmr_df):
    """Generate a summary report of the differential methylation analysis."""
    print("\n" + "="*60)
    print("Step 6: Generating summary report")
    print("="*60)
    
    report_file = OUTPUT_DIR / "differential_methylation_report.txt"
    
    with open(report_file, 'w') as f:
        f.write("="*60 + "\n")
        f.write("Differential Methylation Analysis Report\n")
        f.write("Lake Trout: Siscowet vs Lean\n")
        f.write("="*60 + "\n\n")
        
        f.write("SAMPLE INFORMATION\n")
        f.write("-"*40 + "\n")
        f.write(f"LEAN samples: {', '.join(SAMPLES_LEAN)}\n")
        f.write(f"SISCOWET samples: {', '.join(SAMPLES_SISCOWET)}\n\n")
        
        f.write("ANALYSIS PARAMETERS\n")
        f.write("-"*40 + "\n")
        f.write(f"Minimum coverage per sample: {MIN_COVERAGE}\n")
        f.write(f"Minimum samples per group: {MIN_SAMPLES}\n")
        f.write(f"Methylation difference threshold: {DIFF_THRESHOLD*100}%\n")
        f.write(f"P-value threshold: {P_VALUE_THRESHOLD}\n")
        f.write(f"Q-value threshold (FDR): {Q_VALUE_THRESHOLD}\n")
        f.write(f"DMR merge distance: {DMR_MERGE_DISTANCE} bp\n")
        f.write(f"Minimum CpGs per DMR: {MIN_CPGS_PER_DMR}\n\n")
        
        if dm_results is not None:
            f.write("DIFFERENTIALLY METHYLATED CpGs (DMCs)\n")
            f.write("-"*40 + "\n")
            f.write(f"Total CpG sites tested: {len(dm_results)}\n")
            
            sig_df = dm_results[dm_results['significant']]
            f.write(f"Significant DMCs (p < {P_VALUE_THRESHOLD}): {len(sig_df)}\n")
            
            if len(sig_df) > 0:
                hyper = (sig_df['direction'] == 'hyper_siscowet').sum()
                hypo = (sig_df['direction'] == 'hypo_siscowet').sum()
                f.write(f"  - Hypermethylated in Siscowet: {hyper}\n")
                f.write(f"  - Hypomethylated in Siscowet: {hypo}\n")
            
            sig_fdr = dm_results[dm_results['significant_fdr']]
            f.write(f"Significant after FDR (q < {Q_VALUE_THRESHOLD}): {len(sig_fdr)}\n\n")
        
        if dmr_df is not None and len(dmr_df) > 0:
            f.write("DIFFERENTIALLY METHYLATED REGIONS (DMRs)\n")
            f.write("-"*40 + "\n")
            f.write(f"Total DMRs: {len(dmr_df)}\n")
            
            hyper_dmrs = dmr_df[dmr_df['direction'] == 'hyper_siscowet']
            hypo_dmrs = dmr_df[dmr_df['direction'] == 'hypo_siscowet']
            
            f.write(f"  - Hypermethylated in Siscowet: {len(hyper_dmrs)}\n")
            f.write(f"  - Hypomethylated in Siscowet: {len(hypo_dmrs)}\n")
            f.write(f"\nDMR Statistics:\n")
            f.write(f"  Mean CpGs per DMR: {dmr_df['n_cpgs'].mean():.1f}\n")
            f.write(f"  Mean DMR length: {dmr_df['length'].mean():.1f} bp\n")
            f.write(f"  Mean methylation difference: {dmr_df['mean_diff'].abs().mean():.1f}%\n")
            
            if 'overlapping_genes' in dmr_df.columns:
                n_with_genes = (dmr_df['overlapping_genes'] != '').sum()
                f.write(f"\nDMRs overlapping genes: {n_with_genes}\n")
            
            f.write("\nTop 20 DMRs by methylation difference:\n")
            f.write("-"*40 + "\n")
            top_dmrs = dmr_df.nlargest(20, 'mean_diff', keep='first')
            for _, row in top_dmrs.iterrows():
                genes = row.get('overlapping_genes', '')
                gene_str = f" [{genes}]" if genes else ""
                f.write(f"  {row['dmr_id']}: {row['chrom']}:{row['start']}-{row['end']} ")
                f.write(f"({row['n_cpgs']} CpGs, {row['mean_diff']:.1f}% diff){gene_str}\n")
        
        f.write("\n" + "="*60 + "\n")
        f.write("OUTPUT FILES\n")
        f.write("="*60 + "\n")
        f.write(f"  methylation_matrix.csv - Methylation values per sample\n")
        f.write(f"  differential_methylation_cpgs.csv - All tested CpGs\n")
        f.write(f"  significant_dmcs.csv - Significant DMCs only\n")
        f.write(f"  dmrs.csv - Differentially methylated regions\n")
        f.write(f"  dmrs.bed - DMRs in BED format\n")
        f.write(f"  dmrs_annotated.csv - DMRs with gene annotations\n")
    
    print(f"  Report saved to: {report_file}")
    
    # Print summary to console
    with open(report_file, 'r') as f:
        print("\n" + f.read())

# =============================================================================
# Step 7: Create Visualization Data
# =============================================================================

def create_visualization_data(dm_results, dmr_df):
    """Create data files for visualization (e.g., IGV tracks)."""
    print("\n" + "="*60)
    print("Step 7: Creating visualization data")
    print("="*60)
    
    if dm_results is None:
        return
    
    # Create bedGraph of methylation differences for genome browser
    bedgraph_file = OUTPUT_DIR / "methylation_diff_siscowet_vs_lean.bedGraph"
    
    with open(bedgraph_file, 'w') as f:
        f.write(f'track type=bedGraph name="Meth_Diff_Sisc-Lean" description="Methylation difference (Siscowet - Lean)" visibility=full color=0,0,255 altColor=255,0,0 autoScale=on\n')
        for _, row in dm_results.iterrows():
            f.write(f"{row['chrom']}\t{row['pos']}\t{row['pos']+1}\t{row['meth_diff']:.2f}\n")
    
    print(f"  Created bedGraph: {bedgraph_file}")
    
    # Create significant DMCs BED file
    sig_bed = OUTPUT_DIR / "significant_dmcs.bed"
    sig_df = dm_results[dm_results['significant']]
    
    with open(sig_bed, 'w') as f:
        f.write("#chrom\tstart\tend\tname\tscore\tstrand\n")
        for _, row in sig_df.iterrows():
            score = int(min(abs(row['meth_diff']), 100))
            strand = "+" if row['meth_diff'] > 0 else "-"
            name = f"DMC_{row['chrom']}_{row['pos']}"
            f.write(f"{row['chrom']}\t{row['pos']}\t{row['pos']+1}\t{name}\t{score}\t{strand}\n")
    
    print(f"  Created significant DMCs BED: {sig_bed}")

# =============================================================================
# Main Function
# =============================================================================

def main():
    """Main function to run the complete differential methylation analysis."""
    print("="*60)
    print("Differential Methylation Analysis")
    print("Siscowet vs Lean Lake Trout")
    print("="*60)
    print(f"\nLEAN samples: {', '.join(SAMPLES_LEAN)}")
    print(f"SISCOWET samples: {', '.join(SAMPLES_SISCOWET)}")
    print(f"Methylation data: {METH_DATA_DIR}")
    print(f"Output directory: {OUTPUT_DIR}")
    
    # Ensure output directory exists
    ensure_directory(OUTPUT_DIR)
    
    # Step 1: Download methylation data from gannet server
    n_available = download_methylation_data()
    if n_available < len(SAMPLES):
        print(f"\nWARNING: Only {n_available}/{len(SAMPLES)} samples available.")
    
    # Step 2: Merge methylation data
    result = merge_methylation_data()
    if result is None:
        print("\nERROR: Could not merge methylation data. Exiting.")
        return
    
    meth_matrix, site_info = result
    
    # Step 3: Differential methylation analysis
    dm_results = differential_methylation_analysis(meth_matrix, site_info)
    
    if dm_results is None:
        print("\nERROR: Differential methylation analysis failed. Exiting.")
        return
    
    # Step 4: Identify DMRs
    dmr_df = identify_dmrs(dm_results)
    
    # Step 5: Annotate DMRs with genes
    if dmr_df is not None:
        dmr_df = annotate_dmrs_with_genes(dmr_df)
    
    # Step 6: Generate summary report
    generate_summary_report(dm_results, dmr_df)
    
    # Step 7: Create visualization data
    create_visualization_data(dm_results, dmr_df)
    
    print("\n" + "="*60)
    print("Differential Methylation Analysis Complete!")
    print("="*60)
    print(f"\nOutput files are in: {OUTPUT_DIR}")
    print("\nKey output files:")
    print("  - methylation_matrix.csv          : Per-sample methylation values")
    print("  - differential_methylation_cpgs.csv : All tested CpGs with statistics")
    print("  - significant_dmcs.csv            : Significant DMCs only")
    print("  - significant_dmcs.bed            : Significant DMCs in BED format")
    print("  - dmrs.csv                        : Differentially methylated regions")
    print("  - dmrs.bed                        : DMRs in BED format")
    print("  - dmrs_annotated.csv              : DMRs with gene annotations")
    print("  - methylation_diff_*.bedGraph     : For genome browser visualization")
    print("  - differential_methylation_report.txt : Summary report")

if __name__ == "__main__":
    main()

