[project]
name = "04-pacbio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "modbampy>=0.10.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pysam>=0.23.3",
    "rich>=14.2.0",
    "seaborn>=0.13.2",
]
